---
# Configure migration-planning-guide

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ migration-planning-guide_services_enable }}"
  when: migration-planning-guide_enable_service
